"""Initial migration

Revision ID: 9cb447abe62e
Revises: 
Create Date: 2026-03-06 22:50:18.538008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb447abe62e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_executions_id'), 'tool_executions', ['id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_name'), 'tool_executions', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_tool_name'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_id'), table_name='tool_executions')
    op.drop_table('tool_executions')
    # ### end Alembic commands ###
